apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }} 
  name: {{ .Release.Name }}diskpvc
spec: 
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Release.Name }}disk
  resources:
    requests:
      storage: 5Gi
