apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Name  }} 
  labels:
    app: {{ .Release.Name  }} 
  name: {{ .Release.Name }}svc 
spec:
  type: {{ .Values.xlrelease.serviceType }} 
  selector:
    app: {{ .Release.Name  }} 
  ports:
    - port: 5516
