kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }} 
  name: {{ .Release.Name  }}disk
provisioner: k8s.io/minikube-hostpath
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
