{{ if .Values.xlrelease.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ .Release.Name  }} 
  name: {{ .Release.Name }}-ingress
spec:
  ingressClassName: nginx
  rules:
{{- range .Values.xlrelease.ingress.hosts  }} 
  - host: {{ . }} 
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $.Release.Name }}-svc
            port:
              number: 5516
{{- end }}
{{ end }}
